submit50:
  files: &submit50_files
    - !exclude "*"
    - !include "*.py"
    - !include "*.coe"
    - !require sinuswave.py
    - !require sinus_lut.coe
  
check50:
  files: *submit50_files
  checks: checks/main.py