name: CS50 CI

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  run-cs50-ci:
    name: Run CS50 Continuous Integration
    runs-on: ubuntu-latest

    steps:
      - name: Run CS50 CI Action
        uses: LeoKle/cs50-ci-action@main
        with:
          app-id: ${{ secrets.GH_APP_ID }}
          install-id: ${{ secrets.GH_INSTALL_ID }}
          private-key: ${{ secrets.GH_TOKEN_B64 }}
          problems-repository: ${{ github.repository }}
          problems-branch: ${{ github.event.pull_request.head.ref }}
          solutions-repository: HSDDigitalLabor/solutions
          solutions-branch: main
